const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=['welcome','tester','time','people','mood','constraints','preview','activity','complete','feedback'];
let timerId=null,timerLeft=0,timerRunning=false;
let state={time:30,people:null,groupSize:null,mood:null,constraints:new Set(),session:[],index:0,completed:[],preset:null,feedback:{},events:[],startedAt:Date.now(),buildAt:null,startAt:null,answers:{}};
const quick=[
{id:'q1',type:'Quick',title:'Odd One',min:4,moods:['fun','curious'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'choice',prompt:'Pick the odd one out. There is no official answer — the point is to justify your rule.',choices:['Moon','Mirror','Window','Lake'],after:'Now explain your rule out loud or in one sentence. A weird rule is better than an obvious one.'},
{id:'q2',type:'Quick',title:'Pattern Snap',min:5,moods:['curious'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'check',prompt:'What comes next? 2, 6, 12, 20, 30…',answer:'42',after:'One rule is n(n+1): 1×2, 2×3, 3×4, 4×5, 5×6, so next is 6×7 = 42.'},
{id:'q3',type:'Quick',title:'Five Tiny Wins',min:5,moods:['chill'],people:['solo'],quiet:true,offline:true,battery:true,mode:'text',prompt:'Write five small things that went better than expected this week.',placeholder:'One per line…'},
{id:'q4',type:'Quick',title:'Fast Trivia',min:6,moods:['fun','curious'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'trivia',prompt:'Answer four quick questions without searching.'},
{id:'q5',type:'Quick',title:'Object Remix',min:5,moods:['fun','curious'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'text',prompt:'Pick one object near you. Invent three absurd but technically possible new uses.',placeholder:'Object + three uses…'},
{id:'q6',type:'Quick',title:'Memory Map',min:6,moods:['curious','chill'],people:['solo'],quiet:true,offline:true,battery:true,mode:'timertext',prompt:'Close your eyes for 30 seconds and mentally walk through a familiar room. Then list ten objects in spatial order.',seconds:30,placeholder:'List the objects after the timer…'},
{id:'q7',type:'Quick',title:'Ten-Second Categories',min:5,moods:['fun'],people:['two','group'],quiet:false,offline:true,battery:true,mode:'category',prompt:'Tap start, then name five things before the timer ends.'},
{id:'q8',type:'Quick',title:'Tiny Debate',min:7,moods:['fun','connect','curious'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'timer',prompt:'Defend this opinion for 60 seconds: “Breakfast is the most overrated meal.” Then switch sides.',seconds:60},
{id:'q9',type:'Quick',title:'Three Clues',min:5,moods:['fun','connect'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'text',prompt:'Think of a place you know. Write exactly three clues. No proper nouns.',placeholder:'Clue 1\nClue 2\nClue 3'},
{id:'q10',type:'Quick',title:'One-Minute Story',min:4,moods:['fun'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'timer',prompt:'Tell a story containing a key, a train, and something orange. Stop when the minute ends.',seconds:60},
{id:'q11',type:'Quick',title:'Future Headline',min:5,moods:['curious','chill'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'text',prompt:'Write a newspaper headline from your life one year from now.',placeholder:'Headline…'},
{id:'q12',type:'Quick',title:'Reverse Bucket List',min:6,moods:['chill','connect'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'text',prompt:'List three things you already did that your younger self would have put on a bucket list.',placeholder:'Three things…'}];
const together=[
{id:'t1',type:'Together',title:'Pass the Phone',min:8,moods:['fun','connect'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'pass',prompt:'Pass the phone. Each person privately completes: “I think you’d be surprisingly good at…”'},
{id:'t2',type:'Together',title:'Guess & Reveal',min:8,moods:['fun','connect'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'reveal',prompt:'Person A guesses Person B’s perfect lazy Sunday. Then B writes the real answer and reveals it.'},
{id:'t3',type:'Together',title:'Quick Duel',min:7,moods:['fun'],people:['two','group'],quiet:false,offline:true,battery:true,mode:'duel',prompt:'Best of five. Use rock-paper-scissors, thumb war, coin guess, silent stare, then your own tiebreaker.'},
{id:'t4',type:'Together',title:'Unexpected Question',min:9,moods:['connect','curious'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'revealq',prompt:'Answer the question, then reveal the follow-up.'},
{id:'t5',type:'Together',title:'Same Memory?',min:10,moods:['connect'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'doubletext',prompt:'Pick one shared day. Each person writes the first three details they remember. Compare only after both finish.'},
{id:'t6',type:'Together',title:'Two Truths, One Tiny Lie',min:9,moods:['fun','connect'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'text',prompt:'Write three mundane statements from the last seven days. Make one a believable lie.',placeholder:'1.\n2.\n3.'},
{id:'t7',type:'Together',title:'Rank It Blind',min:10,moods:['fun'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'rank',prompt:'Rank each item from 1–5 before revealing the next. You cannot move earlier items.'},
{id:'t8',type:'Together',title:'Plan a Ridiculous Day',min:12,moods:['fun','connect'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'text',prompt:'You have one free day and a silly imaginary budget. Build the most memorable schedule possible.',placeholder:'09:00…\n12:00…\n18:00…'},
{id:'t9',type:'Together',title:'Compliment With Evidence',min:8,moods:['connect'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'text',prompt:'Write one thing you appreciate about the other person and one specific example that proves it.',placeholder:'I appreciate… because when…'},
{id:'t10',type:'Together',title:'Question Relay',min:11,moods:['connect','curious'],people:['two','group'],quiet:true,offline:true,battery:true,mode:'counter',prompt:'Answer a question, then let your answer inspire the next question. Reach ten turns.'}];
const breaks=['Notice Three Things','Window Reset','Tiny Walk','One Song, Nothing Else','Future Trip','Water + Stretch','Silent Minute × 3','Screen-Free Choice'].map((title,i)=>({id:'b'+(i+1),type:'Break',title,min:[3,5,7,5,6,4,3,10][i],moods:i===4?['connect','chill']:['chill','curious','fun'],people:i===4?['two','group']:['solo','two','group'],quiet:i!==2,offline:true,battery:true,mode:'break',prompt:[
'Put the phone down and find three details around you that you have never consciously noticed.',
'Look into the distance. Let your eyes stop focusing on nearby objects.',
'Put the phone in your pocket and walk until you notice something worth remembering.',
'Play one song you already have. No scrolling while it plays.',
'Put the phone face down. Each person names one place they would travel tomorrow if logistics disappeared.',
'Drink some water and stretch whatever feels stiff. No productivity goal.',
'Do nothing on purpose for three quiet minutes. Notice what your mind reaches for.',
'Choose your own offline thing: tea, shower, balcony, doodle, stretch, conversation. TimeWhim stays out of the way.'
][i]}));
const mystery={id:'m1',type:'Mystery',title:'The Missing Necklace',min:15,moods:['curious','fun'],people:['solo','two','group'],quiet:true,offline:true,battery:true,mode:'mystery',prompt:'A necklace vanished from Room 214 between 18:10 and 18:25. Reveal the clues one by one, then commit to a suspect.'};
const activities=[...quick,...together,...breaks,mystery];
const trivia=[['Largest ocean?','Pacific Ocean'],['Closest planet to the Sun?','Mercury'],['Bones in a typical adult human?','206'],['Capital of Canada?','Ottawa']];
const rankItems=['Beach holiday','Mountain cabin','Big city weekend','Theme park','Road trip'];
function ev(name,data={}){state.events.push({name,t:Date.now(),...data});persist()}
function persist(){localStorage.setItem('timewhim-v05',JSON.stringify({...state,constraints:[...state.constraints]}))}
function cap(x){return String(x).charAt(0).toUpperCase()+String(x).slice(1)}
function show(name){stopTimer();$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$('#progressBar').style.width=(screens.indexOf(name)/(screens.length-1)*100)+'%';window.scrollTo({top:0,behavior:'smooth'});ev('screen_view',{screen:name})}
function setTime(m){state.time=m;$('#timeSlider').value=m;$('#timeNumber').textContent=m>=60?(Math.floor(m/60)+'h'+(m%60?' '+m%60:' ')):m;$('#timeUnit').textContent=m>=60?'available':'minutes';$('#timeRing').style.setProperty('--p',Math.min(100,Math.max(5,m/180*100)))}
function choose(btn,selector,key){$$(selector).forEach(x=>x.classList.toggle('selected',x===btn));state[key]=btn.dataset.v;ev(key+'_selected',{value:state[key]})}
function eligible(a){return a.people.includes(state.people)&&(!state.constraints.has('quiet')||a.quiet)&&(!state.constraints.has('offline')||a.offline)&&(!state.constraints.has('battery')||a.battery)}
function score(a,remaining,last){let s=(a.moods.includes(state.mood)?6:0)+(a.min<=remaining?4:-20)+(last&&last!==a.type?2:0)+(state.completed.includes(a.id)?0:2);return s+Math.random()}
function compose(total){let remaining=total,out=[],last=null,safe=0;while(remaining>=3&&out.length<8&&safe++<30){let pool=activities.filter(eligible).filter(a=>a.min<=remaining).filter(a=>!out.some(x=>x.id===a.id));if(!pool.length)break;pool.sort((a,b)=>score(b,remaining,last)-score(a,remaining,last));let pick=pool[0];out.push(pick);remaining-=pick.min;last=pick.type;if(total>=90&&out.length===3&&remaining>=25){let own=Math.min(45,remaining-10);out.push({id:'own-'+Date.now(),type:'My time',title:'Your own time',min:own,moods:['chill'],people:[state.people],quiet:true,offline:true,battery:true,mode:'break',prompt:'Use this block for your own downloaded film, book, music, nap, view, or anything you already wanted to do.'});remaining-=own;last='My time'}}return out}
function renderPreview(){let total=state.session.reduce((n,a)=>n+a.min,0);$('#previewMinutes').textContent=total;$('#previewMeta').textContent=`Built for ${state.people==='two'?'2':state.people==='group'?(state.groupSize||'group'):'1'} · ${cap(state.mood)}${state.constraints.size?' · '+[...state.constraints].map(cap).join(' · '):''}`;$('#timeline').innerHTML=state.session.map(a=>`<div class="timeline-row"><span class="dot"></span><div><div class="meta">${a.type}</div><div class="title">${a.title}</div></div><div class="duration">${a.min}m</div></div>`).join('')}
function build(){state.buildAt=Date.now();state.people||='solo';state.mood||='curious';state.session=compose(state.time);state.index=0;renderPreview();ev('build',{minutes:state.time});show('preview')}
function startSession(){state.index=0;state.completed=[];state.startAt=Date.now();ev('start_session');renderActivity();show('activity')}
function renderActivity(){stopTimer();if(state.index>=state.session.length)return finishSession();let a=state.session[state.index];$('#remainingText').textContent=state.session.slice(state.index).reduce((n,x)=>n+x.min,0)+' min left';$('#activityType').textContent=a.type.toUpperCase();$('#activityTitle').textContent=a.title;$('#activityPrompt').textContent=a.prompt;$('#activityDuration').textContent=a.min+' minutes';renderAction(a);ev('activity_view',{id:a.id,index:state.index});if(state.index===1)ev('reached_second_activity')}
function renderAction(a){let el=$('#actionArea');el.innerHTML='';const html=s=>{el.innerHTML=s};
if(a.mode==='choice'){html(`<div class="options">${a.choices.map(c=>`<button class="option" data-choice="${c}">${c}</button>`).join('')}</div><div id="actionFeedback"></div>`);$$('[data-choice]').forEach(b=>b.onclick=()=>{$$('[data-choice]').forEach(x=>x.classList.toggle('selected',x===b));$('#actionFeedback').innerHTML=`<div class="feedback ok">${a.after}</div>`;state.answers[a.id]=b.dataset.choice;ev('activity_answer',{id:a.id,answer:b.dataset.choice})})}
else if(a.mode==='check'){html(`<label>Your answer</label><input id="checkInput" type="number" inputmode="numeric"><button class="secondary" id="checkBtn">Check answer</button><div id="actionFeedback"></div>`);$('#checkBtn').onclick=()=>{let v=$('#checkInput').value.trim();let ok=v===a.answer;$('#actionFeedback').innerHTML=`<div class="feedback ${ok?'ok':'warn'}">${ok?'Correct. ':`Not quite. The answer is ${a.answer}. `}${a.after}</div>`;state.answers[a.id]=v;ev('activity_answer',{id:a.id,correct:ok})}}
else if(a.mode==='text'){html(`<label>Your response</label><textarea id="textAnswer" placeholder="${a.placeholder||''}"></textarea><button class="secondary" id="saveAnswer">Save response</button><div id="actionFeedback"></div>`);$('#saveAnswer').onclick=()=>{state.answers[a.id]=$('#textAnswer').value.trim();$('#actionFeedback').innerHTML='<div class="feedback ok">Saved. You can keep going or edit it.</div>';ev('activity_answer',{id:a.id,hasText:!!state.answers[a.id]})}}
else if(a.mode==='trivia'){let n=0;html(`<div id="triviaQ"></div><button class="secondary" id="revealTrivia">Reveal answer</button><button class="secondary" id="nextTrivia">Next question</button>`);let draw=()=>$('#triviaQ').innerHTML=`<h3>${n+1}/4 · ${trivia[n][0]}</h3><div id="triviaAnswer" class="feedback" style="display:none">${trivia[n][1]}</div>`;draw();$('#revealTrivia').onclick=()=>{$('#triviaAnswer').style.display='block';ev('trivia_reveal',{n})};$('#nextTrivia').onclick=()=>{n=Math.min(3,n+1);draw()}}
else if(a.mode==='timer'||a.mode==='break'){let sec=a.seconds||a.min*60;html(timerMarkup(sec,a.mode==='break'?'Put the phone down when you start.':'Start when you are ready.'));wireTimer(sec)}
else if(a.mode==='timertext'){html(timerMarkup(a.seconds,'Close your eyes when the timer starts.')+`<label>After the timer</label><textarea id="textAnswer" placeholder="${a.placeholder}"></textarea>`);wireTimer(a.seconds)}
else if(a.mode==='category'){html(timerMarkup(10,'Category: things you could find in a kitchen. Name five.')+`<div class="counter"><button class="smallbtn" id="minusCount">−</button><strong id="catCount">0</strong><button class="smallbtn" id="plusCount">+</button></div>`);wireTimer(10);let c=0;$('#plusCount').onclick=()=>$('#catCount').textContent=++c;$('#minusCount').onclick=()=>$('#catCount').textContent=c=Math.max(0,c-1)}
else if(a.mode==='pass'){html(`<div class="notice">Person 1: type privately, then tap Hide & pass.</div><textarea id="passText" placeholder="I think you’d be surprisingly good at…"></textarea><button class="secondary" id="passBtn">Hide & pass phone</button><div id="passStage"></div>`);$('#passBtn').onclick=()=>{state.answers[a.id+'-1']=$('#passText').value;$('#passText').value='';$('#passStage').innerHTML='<div class="notice">Person 2: write your sentence, then reveal both.</div><textarea id="passText2"></textarea><button class="secondary" id="revealPass">Reveal both</button>';$('#revealPass').onclick=()=>{$('#passStage').innerHTML=`<div class="feedback"><strong>Person 1:</strong> ${escapeHtml(state.answers[a.id+'-1'])}<br><br><strong>Person 2:</strong> ${escapeHtml($('#passText2').value)}</div>`}}}
else if(a.mode==='reveal'){html(`<label>Person A's guess</label><textarea id="guessA"></textarea><button class="secondary" id="lockGuess">Lock guess & pass</button><div id="revealArea"></div>`);$('#lockGuess').onclick=()=>{$('#revealArea').innerHTML='<label>Person B’s real answer</label><textarea id="realB"></textarea><button class="secondary" id="showBoth">Reveal both</button>';$('#showBoth').onclick=()=>{$('#revealArea').innerHTML=`<div class="feedback"><strong>Guess:</strong> ${escapeHtml($('#guessA').value)}<br><br><strong>Real answer:</strong> ${escapeHtml($('#realB').value)}</div>`}}}
else if(a.mode==='duel'){html(`<div class="score"><div class="scorebox">Player 1<strong id="s1">0</strong><button class="smallbtn" id="p1">+ point</button></div><div class="scorebox">Player 2<strong id="s2">0</strong><button class="smallbtn" id="p2">+ point</button></div></div><div id="duelFeedback"></div>`);let s1=0,s2=0;let draw=()=>{ $('#s1').textContent=s1;$('#s2').textContent=s2;if(s1===3||s2===3)$('#duelFeedback').innerHTML=`<div class="feedback ok">${s1===3?'Player 1':'Player 2'} wins the duel.</div>`};$('#p1').onclick=()=>{if(s1<3&&s2<3)s1++;draw()};$('#p2').onclick=()=>{if(s1<3&&s2<3)s2++;draw()}}
else if(a.mode==='revealq'){html(`<div class="feedback">What belief or taste of yours changed completely in the last five years?</div><button class="secondary" id="followQ">Reveal follow-up</button><div id="followArea"></div>`);$('#followQ').onclick=()=>$('#followArea').innerHTML='<div class="feedback ok">What specific moment, person, or experience caused that change?</div>'}
else if(a.mode==='doubletext'){html('<label>Person A</label><textarea id="aText"></textarea><label>Person B</label><textarea id="bText"></textarea><button class="secondary" id="compareText">Compare</button><div id="compareArea"></div>');$('#compareText').onclick=()=>$('#compareArea').innerHTML=`<div class="feedback"><strong>A:</strong> ${escapeHtml($('#aText').value)}<br><br><strong>B:</strong> ${escapeHtml($('#bText').value)}</div>`}
else if(a.mode==='rank'){let i=0,ranked=[];html(`<div id="rankItem"></div><div class="options" id="rankBtns">${[1,2,3,4,5].map(n=>`<button class="option" data-rank="${n}">Rank ${n}</button>`).join('')}</div><div id="rankResult"></div>`);let draw=()=>$('#rankItem').innerHTML=`<h3>Item ${i+1}/5</h3><div class="feedback">${rankItems[i]}</div>`;draw();$$('[data-rank]').forEach(b=>b.onclick=()=>{if(ranked.some(x=>x.rank===+b.dataset.rank))return;ranked.push({item:rankItems[i],rank:+b.dataset.rank});i++;if(i<5)draw();else{$('#rankBtns').style.display='none';$('#rankItem').style.display='none';$('#rankResult').innerHTML='<div class="feedback ok">'+ranked.sort((a,b)=>a.rank-b.rank).map(x=>`${x.rank}. ${x.item}`).join('<br>')+'</div>'}})}
else if(a.mode==='counter'){let c=0;html(`<div class="counter"><button class="smallbtn" id="minusTurn">−</button><strong id="turnCount">0 / 10</strong><button class="smallbtn" id="plusTurn">+</button></div><div id="turnFeedback"></div>`);let draw=()=>{ $('#turnCount').textContent=`${c} / 10`;if(c>=10)$('#turnFeedback').innerHTML='<div class="feedback ok">Relay complete.</div>'};$('#plusTurn').onclick=()=>{c=Math.min(10,c+1);draw()};$('#minusTurn').onclick=()=>{c=Math.max(0,c-1);draw()}}
else if(a.mode==='mystery'){renderMystery(el)}
}
function timerMarkup(sec,note){return `<div class="timer"><div class="timer-display" id="timerDisplay">${fmt(sec)}</div><div class="tiny">${note}</div><div class="timer-row"><button class="smallbtn" id="timerStart">Start</button><button class="smallbtn" id="timerPause">Pause</button><button class="smallbtn" id="timerReset">Reset</button></div></div>`}
function wireTimer(sec){timerLeft=sec;$('#timerStart').onclick=()=>startTimer();$('#timerPause').onclick=()=>pauseTimer();$('#timerReset').onclick=()=>{stopTimer();timerLeft=sec;$('#timerDisplay').textContent=fmt(timerLeft)}}
function startTimer(){if(timerRunning)return;timerRunning=true;timerId=setInterval(()=>{timerLeft=Math.max(0,timerLeft-1);let d=$('#timerDisplay');if(d)d.textContent=fmt(timerLeft);if(timerLeft===0){stopTimer();ev('timer_finished')}} ,1000);ev('timer_started')}
function pauseTimer(){if(!timerRunning)return;clearInterval(timerId);timerId=null;timerRunning=false;ev('timer_paused',{secondsLeft:timerLeft})}
function stopTimer(){if(timerId)clearInterval(timerId);timerId=null;timerRunning=false}
function fmt(s){return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function renderMystery(el){const clues=['The balcony door was locked from inside.','Wet shoe marks stop before the carpet, not at the balcony.','The cleaner logged out at 18:12.','A guest heard a service cart at 18:18.','The night porter had access to a master key and the service cart.'];let n=0;el.innerHTML=`<div class="clues" id="clueList">${clues.map((c,i)=>`<button class="clue locked" data-clue="${i}">Clue ${i+1}: ${c}</button>`).join('')}</div><div id="mysteryDecision" style="display:none"><h3>Your theory</h3><div class="options">${['Cleaner','Guest’s friend','Night porter'].map(x=>`<button class="option" data-suspect="${x}">${x}</button>`).join('')}</div><textarea id="mysteryWhy" placeholder="Why?"></textarea><button class="secondary" id="revealMystery">Reveal strongest theory</button><div id="mysteryResult"></div></div>`;$$('[data-clue]').forEach(b=>b.onclick=()=>{if(!b.classList.contains('locked'))return;b.classList.remove('locked');n++;ev('mystery_clue_revealed',{n});if(n===clues.length)$('#mysteryDecision').style.display='block'});let suspect='';$$('[data-suspect]').forEach(b=>b.onclick=()=>{suspect=b.dataset.suspect;$$('[data-suspect]').forEach(x=>x.classList.toggle('selected',x===b))});$('#revealMystery').onclick=()=>{state.answers.m1={suspect,why:$('#mysteryWhy').value};$('#mysteryResult').innerHTML='<div class="feedback ok"><strong>Strongest theory: Night porter.</strong><br><br>The 18:18 service cart plus master-key access fit the time window best. The wet shoe marks suggest a staged outdoor story rather than a balcony entry. This is a reasoning puzzle, so a different theory is valid if your explanation handles every clue.</div>';ev('mystery_theory',{suspect})}}
function completeActivity(){let a=state.session[state.index];state.completed.push(a.id);ev('activity_complete',{id:a.id});state.index++;renderActivity()}
function swap(){let old=state.session[state.index],r=old.min+2;let pool=activities.filter(eligible).filter(a=>a.id!==old.id&&a.min<=r);if(pool.length){pool.sort((a,b)=>score(b,r,old.type)-score(a,r,old.type));state.session[state.index]=pool[0]}ev('swap',{from:old.id,to:state.session[state.index].id});renderActivity()}
function shorter(){let old=state.session[state.index],pool=activities.filter(eligible).filter(a=>a.id!==old.id&&a.min<old.min).sort((a,b)=>a.min-b.min);if(pool[0])state.session[state.index]=pool[0];ev('shorter',{from:old.id,to:state.session[state.index].id});renderActivity()}
function replan(reason){let used=state.session.slice(0,state.index).reduce((n,a)=>n+a.min,0),remaining=Math.max(5,state.time-used);state.session=[...state.session.slice(0,state.index),...compose(remaining)];ev('replan',{reason,remaining});closeDialogs();renderActivity()}
function finishSession(){stopTimer();let mins=state.session.slice(0,Math.min(state.index,state.session.length)).reduce((n,a)=>n+a.min,0);$('#doneMinutes').textContent=mins+' min';$('#doneCount').textContent=state.completed.length+' activities';ev('session_complete',{mins,count:state.completed.length});show('complete')}
function exportReport(){$$('[data-field]').forEach(x=>state.feedback[x.dataset.field]=x.value);let r={schema:'timewhim-tester-v0.5',exportedAt:new Date().toISOString(),setup:{timeMinutes:state.time,people:state.people,groupSize:state.groupSize,mood:state.mood,constraints:[...state.constraints]},completedActivities:state.completed,answers:state.answers,feedback:state.feedback,events:state.events.map((e,i)=>({...e,relativeMs:e.t-state.events[0].t,t:undefined}))};let blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='timewhim-test-'+Date.now()+'.json';a.click();URL.revokeObjectURL(u);ev('report_exported')}
function closeDialogs(){$$('dialog[open]').forEach(d=>d.close())}
function escapeHtml(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function init(){
$('#getStarted').onclick=()=>show('tester');$$('[data-preset]').forEach(b=>b.onclick=()=>{let p=b.dataset.preset;state.preset=p;if(p==='natural'){setTime(30);state.people='solo';state.mood='curious';state.constraints=new Set()}if(p==='social'){setTime(45);state.people='two';state.mood='fun';state.constraints=new Set(['quiet'])}if(p==='travel'){setTime(150);state.people='solo';state.mood='chill';state.constraints=new Set(['offline','battery'])}syncSetup();show('constraints')});$('#chooseFreely').onclick=()=>show('time');
$$('[data-min]').forEach(b=>b.onclick=()=>{setTime(+b.dataset.min);$$('[data-min]').forEach(x=>x.classList.toggle('selected',x===b))});$('#timeSlider').oninput=e=>setTime(+e.target.value);$('#timeNext').onclick=()=>show('people');
$$('#peopleChoices .choice').forEach(b=>b.onclick=()=>{choose(b,'#peopleChoices .choice','people');$('#groupSize').style.display=state.people==='group'?'flex':'none';$('#peopleNext').disabled=false});$$('#groupSize .chip').forEach(b=>b.onclick=()=>choose(b,'#groupSize .chip','groupSize'));$('#peopleNext').onclick=()=>show('mood');
$$('#moodChoices .choice').forEach(b=>b.onclick=()=>{choose(b,'#moodChoices .choice','mood');$('#moodNext').disabled=false});$('#surpriseMood').onclick=()=>{state.mood=['fun','curious','chill','connect'][Math.floor(Math.random()*4)];syncSetup();$('#moodNext').disabled=false;ev('mood_surprise',{mood:state.mood})};$('#moodNext').onclick=()=>show('constraints');
$$('#constraintChips .chip').forEach(b=>b.onclick=()=>{let v=b.dataset.v;state.constraints.has(v)?state.constraints.delete(v):state.constraints.add(v);b.classList.toggle('selected');ev('constraint',{v,on:state.constraints.has(v)})});$('#buildBtn').onclick=build;$('#mixBtn').onclick=()=>{state.session=compose(state.time);renderPreview();ev('mix')};$('#startBtn').onclick=startSession;$('#doneNext').onclick=completeActivity;$('#swapBtn').onclick=swap;$('#shorterBtn').onclick=shorter;$('#moodBtn').onclick=()=>$('#moodDialog').showModal();$('#moreBtn').onclick=()=>$('#moreDialog').showModal();$$('[data-replan]').forEach(b=>b.onclick=()=>{if(b.dataset.replan==='quiet')state.constraints.add('quiet');if(b.dataset.replan==='less')state.time=Math.max(10,Math.round(state.time*.7));if(b.dataset.replan==='people')state.people=state.people==='solo'?'two':'group';if(['fun','chill','connect','curious'].includes(b.dataset.replan))state.mood=b.dataset.replan;replan(b.dataset.replan)});$('#finishNow').onclick=finishSession;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$$('.feedback-row').forEach(row=>$$('button',row).forEach(b=>b.onclick=()=>{[...row.querySelectorAll('button')].forEach(x=>x.classList.toggle('selected',x===b));state.feedback[row.dataset.key]=b.textContent;ev('feedback_choice',{key:row.dataset.key,value:b.textContent})}));$('#toFeedback').onclick=()=>show('feedback');$('#exportBtn').onclick=exportReport;$('#restartBtn').onclick=()=>location.reload();$('#feedbackDone').onclick=()=>show('welcome');setTime(30);ev('app_open')}
function syncSetup(){$$('#peopleChoices .choice').forEach(b=>b.classList.toggle('selected',b.dataset.v===state.people));$$('#moodChoices .choice').forEach(b=>b.classList.toggle('selected',b.dataset.v===state.mood));$$('#constraintChips .chip').forEach(b=>b.classList.toggle('selected',state.constraints.has(b.dataset.v)))}
init();